###
GET http://localhost:3000/api/v1/authors

###
GET http://localhost:3000/api/v1/authors/1
###
POST http://localhost:3000/api/v1/authors
Content-Type:  application/json

{
  "author": {
    "name" : "RubyApit",
    "CPF" : "07661881498"
  }
}

###
PUT http://localhost:3000/api/v1/authors/2
Content-Type:  application/json

{
  "author": {
    "name" : "trocoutres",
    "CPF" : "16665881491"
  }
}

###
DELETE http://localhost:3000/api/v1/authors/3

###
